---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 3000, host: 3000}]
    - ["forwarded_port", {guest: 80, host: 80}]
provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[sensu-demo::sensu-server]
    attributes:
        sensu:
            use_ssl: false
